# Session 7 Lab
Transactions and Views in SQLite.

In [ ]:
import sqlite3, pandas as pd
conn = sqlite3.connect('session7_lab.db')
print('Connected')

In [ ]:
# Simple view
conn.execute('CREATE VIEW emp_contact AS SELECT first_name, salary FROM employees;')
pd.read_sql_query('SELECT * FROM emp_contact;', conn)

In [ ]:
# Transaction with savepoint
conn.execute('BEGIN')
conn.execute('SAVEPOINT sp1')
conn.execute('UPDATE employees SET salary=salary+1000 WHERE dept_id=1')
conn.execute('ROLLBACK TO sp1')
conn.commit()